#!/bin/sh

if read -r proto cookie && [ -n "$DISPLAY" ]; then
  if [ "$(echo "$DISPLAY" | cut -c1-10)" = 'localhost:' ]; then
    # X11UseLocalhost=yes
    echo add "unix:$(echo "$DISPLAY" | cut -c11-)" "$proto" "$cookie"
  else
    # X11UseLocalhost=no
    echo add "$DISPLAY" "$proto" "$cookie"
  fi | xauth -q -
fi

if [ -n "$SSH_CONNECTION" ] && [ -S "$SSH_AUTH_SOCK" ]; then
  case "$SSH_AUTH_SOCK" in
    /tmp/ssh-*)
      ln -sf "$SSH_AUTH_SOCK" "$HOME/.ssh/ssh_auth_sock"
      export SSH_AUTH_SOCK="$HOME/.ssh/ssh_auth_sock"
      ;;
  esac
fi
